---
- name: Check disk space
  hosts: all
  become: yes
  tasks:
    - name: Get disk usage
      command: df -h /
      register: disk_usage

    - name: Print disk usage
      debug:
        var: disk_usage.stdout_lines
