---
- name: Pull and run a Docker container
  hosts: webservers
  become: yes
  tasks:
    - name: Pull nginx image (optional if already pulled)
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Run nginx container
      community.docker.docker_container:
        name: nginx_server
        image: nginx
        state: started
        restart_policy: always
        published_ports:
          - "8082:80"
