apiVersion: apps/v1
kind: Deployment
metadata:
  name: unapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: cont1
        image: nginx
        ports:
        - containerPort: 80
